
package org.kiwi.dictao.webservices.d3s.Authority;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CertificatePort", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2/Authority")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CertificatePort {


    /**
     * 
     * @param certificate
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:create")
    @WebResult(name = "createdResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "createCertificate", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateCertificate")
    @ResponseWrapper(localName = "createCertificateResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateResponse")
    public String createCertificate(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "certificate", targetNamespace = "")
        Certificate certificate)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.Certificate
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:read")
    @WebResult(name = "certificate", targetNamespace = "")
    @RequestWrapper(localName = "readCertificate", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Read")
    @ResponseWrapper(localName = "readCertificateResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ReadCertificateResponse")
    public Certificate readCertificate(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param certificate
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:update")
    @WebResult(name = "updatedResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "updateCertificate", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateCertificate")
    @ResponseWrapper(localName = "updateCertificateResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateResponse")
    public String updateCertificate(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath,
        @WebParam(name = "certificate", targetNamespace = "")
        Certificate certificate)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:delete")
    @RequestWrapper(localName = "deleteCertificate", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Delete")
    @ResponseWrapper(localName = "deleteCertificateResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.DeleteResponse")
    public void deleteCertificate(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param orderBy
     * @param criteria
     * @param searchPath
     * @param motivation
     * @param maxResult
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.FindCertificatesResponse
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:find")
    @WebResult(name = "findCertificatesResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority")
    @RequestWrapper(localName = "findCertificates", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.FindCertificates")
    @ResponseWrapper(localName = "findCertificatesResponseContent", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.FindCertificatesResponseContent")
    public FindCertificatesResponse findCertificates(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "searchPath", targetNamespace = "")
        String searchPath,
        @WebParam(name = "criteria", targetNamespace = "")
        List<Criterion> criteria,
        @WebParam(name = "orderBy", targetNamespace = "")
        List<OrderBy> orderBy,
        @WebParam(name = "maxResult", targetNamespace = "")
        int maxResult)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param cursor
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.FindCertificatesResponse
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Certificate:next")
    @WebResult(name = "findCertificatesResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority")
    @RequestWrapper(localName = "nextCertificates", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.NextCertificates")
    @ResponseWrapper(localName = "nextCertificatesResponseContent", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.NextCertificatesResponseContent")
    public FindCertificatesResponse nextCertificates(
        @WebParam(name = "cursor", targetNamespace = "")
        byte[] cursor)
        throws EnvironmentFaultException, UserFaultException
    ;

}
