
package org.kiwi.dictao.webservices.d3s.Authority;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrgunitPort", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2/Authority")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrgunitPort {


    /**
     * 
     * @param orgunit
     * @param containerPath
     * @param firstUserRolePath
     * @param firstUserPath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Orgunit:create")
    @WebResult(name = "createdResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "createOrgunit", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateOrgunit")
    @ResponseWrapper(localName = "createOrgunitResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateResponse")
    public String createOrgunit(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "containerPath", targetNamespace = "")
        String containerPath,
        @WebParam(name = "orgunit", targetNamespace = "")
        Orgunit orgunit,
        @WebParam(name = "firstUserPath", targetNamespace = "")
        String firstUserPath,
        @WebParam(name = "firstUserRolePath", targetNamespace = "")
        String firstUserRolePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.Orgunit
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Orgunit:read")
    @WebResult(name = "orgunit", targetNamespace = "")
    @RequestWrapper(localName = "readOrgunit", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Read")
    @ResponseWrapper(localName = "readOrgunitResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ReadOrgunitResponse")
    public Orgunit readOrgunit(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param orgunit
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Orgunit:update")
    @WebResult(name = "updatedResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "updateOrgunit", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateOrgunit")
    @ResponseWrapper(localName = "updateOrgunitResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateResponse")
    public String updateOrgunit(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath,
        @WebParam(name = "orgunit", targetNamespace = "")
        Orgunit orgunit)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Orgunit:delete")
    @RequestWrapper(localName = "deleteOrgunit", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Delete")
    @ResponseWrapper(localName = "deleteOrgunitResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.DeleteResponse")
    public void deleteOrgunit(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

}
