
package org.kiwi.dictao.webservices.d3s.Authority;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserPort", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2/Authority")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPort {


    /**
     * 
     * @param motivation
     * @param user
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:create")
    @WebResult(name = "createdResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateResponse")
    public String createUser(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.User
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:read")
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "readUser", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Read")
    @ResponseWrapper(localName = "readUserResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ReadUserResponse")
    public User readUser(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param user
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:update")
    @WebResult(name = "updatedResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateResponse")
    public String updateUser(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath,
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:delete")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Delete")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.DeleteResponse")
    public void deleteUser(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param authorizations
     * @param motivation
     * @param userPath
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:addAuthorizations")
    @RequestWrapper(localName = "addAuthorizations", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.AddAuthorizations")
    @ResponseWrapper(localName = "addAuthorizationsResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.AddAuthorizationsResponse")
    public void addAuthorizations(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "userPath", targetNamespace = "")
        String userPath,
        @WebParam(name = "authorizations", targetNamespace = "")
        Authorizations authorizations)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param authorizations
     * @param motivation
     * @param userPath
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "User:removeAuthorizations")
    @RequestWrapper(localName = "removeAuthorizations", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.RemoveAuthorizations")
    @ResponseWrapper(localName = "removeAuthorizationsResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.RemoveAuthorizationsResponse")
    public void removeAuthorizations(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "userPath", targetNamespace = "")
        String userPath,
        @WebParam(name = "authorizations", targetNamespace = "")
        Authorizations authorizations)
        throws EnvironmentFaultException, UserFaultException
    ;

}
