
package org.kiwi.dictao.webservices.d3s.Storage;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Storage", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2/Storage", wsdlLocation = "file:/C:/local_projects/java/librairies/dictao/wsdl/v2_1_Storage.wsdl")
public class Storage
    extends Service
{

    private final static URL STORAGE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kiwi.dictao.webservices.d3s.Storage.Storage.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kiwi.dictao.webservices.d3s.Storage.Storage.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/local_projects/java/librairies/dictao/wsdl/v2_1_Storage.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/local_projects/java/librairies/dictao/wsdl/v2_1_Storage.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STORAGE_WSDL_LOCATION = url;
    }

    public Storage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Storage() {
        super(STORAGE_WSDL_LOCATION, new QName("http://www.dictao.com/d3s/wsdl/v2/Storage", "Storage"));
    }

    /**
     * 
     * @return
     *     returns SecretPort
     */
    @WebEndpoint(name = "SecretPort")
    public SecretPort getSecretPort() {
        return super.getPort(new QName("http://www.dictao.com/d3s/wsdl/v2/Storage", "SecretPort"), SecretPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecretPort
     */
    @WebEndpoint(name = "SecretPort")
    public SecretPort getSecretPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dictao.com/d3s/wsdl/v2/Storage", "SecretPort"), SecretPort.class, features);
    }

}
