
package org.kiwi.dictao.webservices.dvs.provisioning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DVSProvisioningFrontEnd", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DVSProvisioningFrontEnd {


    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param addUserListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.AddUserListResponse
     */
    @WebMethod(operationName = "AddUserList", action = "http://www.dictao.com/DVS/FrontEnd/AddUserList")
    @WebResult(name = "AddUserListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "AddUserListResponse")
    public AddUserListResponse addUserList(
        @WebParam(name = "AddUserListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "AddUserListRequest")
        AddUserListRequest addUserListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param getUserListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.GetUserListResponse
     */
    @WebMethod(operationName = "GetUserList", action = "http://www.dictao.com/DVS/FrontEnd/GetUserList")
    @WebResult(name = "GetUserListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetUserListResponse")
    public GetUserListResponse getUserList(
        @WebParam(name = "GetUserListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetUserListRequest")
        GetUserListRequest getUserListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param deleteUserInformationListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.DeleteUserInformationListResponse
     */
    @WebMethod(operationName = "DeleteUserInformationList", action = "http://www.dictao.com/DVS/FrontEnd/DeleteUserInformationList")
    @WebResult(name = "DeleteUserInformationListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "DeleteUserInformationListResponse")
    public DeleteUserInformationListResponse deleteUserInformationList(
        @WebParam(name = "DeleteUserInformationListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "DeleteUserInformationListRequest")
        DeleteUserInformationListRequest deleteUserInformationListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param addProfileListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.AddProfileListResponse
     */
    @WebMethod(operationName = "AddProfileList", action = "http://www.dictao.com/DVS/FrontEnd/AddProfileList")
    @WebResult(name = "AddProfileListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "AddProfileListResponse")
    public AddProfileListResponse addProfileList(
        @WebParam(name = "AddProfileListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "AddProfileListRequest")
        AddProfileListRequest addProfileListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param getProfileListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.GetProfileListResponse
     */
    @WebMethod(operationName = "GetProfileList", action = "http://www.dictao.com/DVS/FrontEnd/GetProfileList")
    @WebResult(name = "GetProfileListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetProfileListResponse")
    public GetProfileListResponse getProfileList(
        @WebParam(name = "GetProfileListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetProfileListRequest")
        GetProfileListRequest getProfileListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param deleteProfileListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.DeleteProfileListResponse
     */
    @WebMethod(operationName = "DeleteProfileList", action = "http://www.dictao.com/DVS/FrontEnd/DeleteProfileList")
    @WebResult(name = "DeleteProfileListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "DeleteProfileListResponse")
    public DeleteProfileListResponse deleteProfileList(
        @WebParam(name = "DeleteProfileListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "DeleteProfileListRequest")
        DeleteProfileListRequest deleteProfileListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param synchronizeUserListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.SynchronizeUserListResponse
     */
    @WebMethod(operationName = "SynchronizeUserList", action = "http://www.dictao.com/DVS/FrontEnd/SynchronizeUserList")
    @WebResult(name = "SynchronizeUserListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "SynchronizeUserListResponse")
    public SynchronizeUserListResponse synchronizeUserList(
        @WebParam(name = "SynchronizeUserListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "SynchronizeUserListRequest")
        SynchronizeUserListRequest synchronizeUserListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param getDeviceSensitiveValueRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.GetDeviceSensitiveValueResponse
     */
    @WebMethod(operationName = "GetDeviceSensitiveValue", action = "http://www.dictao.com/DVS/FrontEnd/GetDeviceSensitiveValue")
    @WebResult(name = "GetDeviceSensitiveValueResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetDeviceSensitiveValueResponse")
    public GetDeviceSensitiveValueResponse getDeviceSensitiveValue(
        @WebParam(name = "GetDeviceSensitiveValueRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetDeviceSensitiveValueRequest")
        GetDeviceSensitiveValueRequest getDeviceSensitiveValueRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param linkDeviceListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.LinkDeviceListResponse
     */
    @WebMethod(operationName = "LinkDeviceList", action = "http://www.dictao.com/DVS/FrontEnd/LinkDeviceList")
    @WebResult(name = "LinkDeviceListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "LinkDeviceListResponse")
    public LinkDeviceListResponse linkDeviceList(
        @WebParam(name = "LinkDeviceListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "LinkDeviceListRequest")
        LinkDeviceListRequest linkDeviceListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param searchTokenKeyListRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.SearchTokenKeyListResponse
     */
    @WebMethod(operationName = "SearchTokenKeyList", action = "http://www.dictao.com/DVS/FrontEnd/SearchTokenKeyList")
    @WebResult(name = "SearchTokenKeyListResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "SearchTokenKeyListResponse")
    public SearchTokenKeyListResponse searchTokenKeyList(
        @WebParam(name = "SearchTokenKeyListRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "SearchTokenKeyListRequest")
        SearchTokenKeyListRequest searchTokenKeyListRequest);

    /**
     * Add a list of users in Dictao Validation Server
     * 
     * @param getTokenKeyValueRequest
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.provisioning.GetTokenKeyValueResponse
     */
    @WebMethod(operationName = "GetTokenKeyValue", action = "http://www.dictao.com/DVS/FrontEnd/GetTokenKeyValue")
    @WebResult(name = "GetTokenKeyValueResponse", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetTokenKeyValueResponse")
    public GetTokenKeyValueResponse getTokenKeyValue(
        @WebParam(name = "GetTokenKeyValueRequest", targetNamespace = "http://www.dictao.com/DVS/FrontEnd/Provisioning", partName = "GetTokenKeyValueRequest")
        GetTokenKeyValueRequest getTokenKeyValueRequest);

}
