
package org.kiwi.dictao.webservices.dsam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DSAMSoap", targetNamespace = "http://www.dictao.com/DSAM/Interface")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DSAMSoap {


    /**
     * 
     * @param documentType
     * @param requestId
     * @param tag
     * @param signature
     * @return
     *     returns org.kiwi.dictao.webservices.dsam.DSAMResponse
     */
    @WebMethod(operationName = "DSAMverifySignature", action = "http://www.dictao.com/DSAM/Interface/DSAMverifySignature")
    @WebResult(name = "DSAMverifySignatureResult", targetNamespace = "http://www.dictao.com/DSAM/Interface")
    @RequestWrapper(localName = "DSAMverifySignature", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.DSAMverifySignature")
    @ResponseWrapper(localName = "DSAMverifySignatureResponse", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.DSAMverifySignatureResponse")
    public DSAMResponse dsaMverifySignature(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String requestId,
        @WebParam(name = "documentType", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String documentType,
        @WebParam(name = "signature", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        DataType signature,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String tag);

    /**
     * 
     * @param certificate
     * @param refreshCRLs
     * @param documentType
     * @param pluginParameter
     * @param requestId
     * @param tag
     * @param signedData
     * @param signedDataHash
     * @param signature
     * @return
     *     returns org.kiwi.dictao.webservices.dsam.DSAMResponse
     */
    @WebMethod(operationName = "DSAMverifySignatureEx", action = "http://www.dictao.com/DSAM/Interface/DSAMverifySignatureEx")
    @WebResult(name = "DSAMverifySignatureResult", targetNamespace = "http://www.dictao.com/DSAM/Interface")
    @RequestWrapper(localName = "DSAMverifySignatureEx", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.DSAMverifySignatureEx")
    @ResponseWrapper(localName = "DSAMverifySignatureExResponse", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.DSAMverifySignatureExResponse")
    public DSAMResponse dsaMverifySignatureEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String requestId,
        @WebParam(name = "documentType", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String documentType,
        @WebParam(name = "signature", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        DataType signature,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String tag,
        @WebParam(name = "refreshCRLs", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        int refreshCRLs,
        @WebParam(name = "signedData", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        DataType signedData,
        @WebParam(name = "signedDataHash", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String signedDataHash,
        @WebParam(name = "certificate", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        String certificate,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param dsamProofId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDSAMProof", action = "http://www.dictao.com/DSAM/Interface/GetDSAMProof")
    @WebResult(name = "DSAMProof", targetNamespace = "http://www.dictao.com/DSAM/Interface")
    @RequestWrapper(localName = "GetDSAMProof", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.GetDSAMProof")
    @ResponseWrapper(localName = "GetDSAMProofResponse", targetNamespace = "http://www.dictao.com/DSAM/Interface", className = "org.kiwi.dictao.webservices.dsam.GetDSAMProofResponse")
    public String getDSAMProof(
        @WebParam(name = "DSAMProofId", targetNamespace = "http://www.dictao.com/DSAM/Interface")
        long dsamProofId);

}
