
package org.kiwi.dictao.webservices.dtss;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Dictao Validation Server v4.7
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DTSS", targetNamespace = "http://www.dictao.com/DTSS/Interface", wsdlLocation = "file:/C:/local_projects/java/librairies/dictao/wsdl/DTSSInterfaceFrontEnd.wsdl")
public class DTSS
    extends Service
{

    private final static URL DTSS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kiwi.dictao.webservices.dtss.DTSS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kiwi.dictao.webservices.dtss.DTSS.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/local_projects/java/librairies/dictao/wsdl/DTSSInterfaceFrontEnd.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/local_projects/java/librairies/dictao/wsdl/DTSSInterfaceFrontEnd.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DTSS_WSDL_LOCATION = url;
    }

    public DTSS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DTSS() {
        super(DTSS_WSDL_LOCATION, new QName("http://www.dictao.com/DTSS/Interface", "DTSS"));
    }

    /**
     * 
     * @return
     *     returns DTSSSoap
     */
    @WebEndpoint(name = "DTSSSoap")
    public DTSSSoap getDTSSSoap() {
        return super.getPort(new QName("http://www.dictao.com/DTSS/Interface", "DTSSSoap"), DTSSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DTSSSoap
     */
    @WebEndpoint(name = "DTSSSoap")
    public DTSSSoap getDTSSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dictao.com/DTSS/Interface", "DTSSSoap"), DTSSSoap.class, features);
    }

}
