
package org.kiwi.dictao.webservices.dvs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Dictao Validation Server v4.8
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DVS", targetNamespace = "http://www.dictao.com/DVS/Interface", wsdlLocation = "file:/C:/local_projects/java/librairies/dictao/wsdl/DVSInterfaceFrontEnd.wsdl")
public class DVS
    extends Service
{

    private final static URL DVS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kiwi.dictao.webservices.dvs.DVS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kiwi.dictao.webservices.dvs.DVS.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/local_projects/java/librairies/dictao/wsdl/DVSInterfaceFrontEnd.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/local_projects/java/librairies/dictao/wsdl/DVSInterfaceFrontEnd.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DVS_WSDL_LOCATION = url;
    }

    public DVS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DVS() {
        super(DVS_WSDL_LOCATION, new QName("http://www.dictao.com/DVS/Interface", "DVS"));
    }

    /**
     * 
     * @return
     *     returns DVSSoap
     */
    @WebEndpoint(name = "DVSSoap")
    public DVSSoap getDVSSoap() {
        return super.getPort(new QName("http://www.dictao.com/DVS/Interface", "DVSSoap"), DVSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DVSSoap
     */
    @WebEndpoint(name = "DVSSoap")
    public DVSSoap getDVSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dictao.com/DVS/Interface", "DVSSoap"), DVSSoap.class, features);
    }

}
