
package org.kiwi.dictao.webservices.dvs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DVSSoap", targetNamespace = "http://www.dictao.com/DVS/Interface")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DVSSoap {


    /**
     * 
     * @param certificate
     * @param refreshCRLs
     * @param transactionId
     * @param pluginParameter
     * @param requestId
     * @param tag
     * @param signedData
     * @param signedDataHash
     * @param properties
     * @param signature
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/verifySignatureEx")
    @WebResult(name = "verifySignatureExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "verifySignatureEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifySignatureEx")
    @ResponseWrapper(localName = "verifySignatureExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifySignatureExResponse")
    public DVSResponseEx verifySignatureEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "refreshCRLs", targetNamespace = "http://www.dictao.com/DVS/Interface")
        int refreshCRLs,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "signature", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType signature,
        @WebParam(name = "signedData", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType signedData,
        @WebParam(name = "signedDataHash", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String signedDataHash,
        @WebParam(name = "certificate", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String certificate,
        @WebParam(name = "properties", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String properties,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param certificate
     * @param transactionId
     * @param pluginParameter
     * @param decryptionType
     * @param requestId
     * @param tag
     * @param dataToDecrypt
     * @param decryptionFormat
     * @param decryptionParameter
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSDecryptResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/decryptEx")
    @WebResult(name = "decryptExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "decryptEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.DecryptEx")
    @ResponseWrapper(localName = "decryptExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.DecryptExResponse")
    public DVSDecryptResponseEx decryptEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "dataToDecrypt", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType dataToDecrypt,
        @WebParam(name = "certificate", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String certificate,
        @WebParam(name = "decryptionFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String decryptionFormat,
        @WebParam(name = "decryptionType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String decryptionType,
        @WebParam(name = "decryptionParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String decryptionParameter,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param certificate
     * @param refreshCRLs
     * @param transactionId
     * @param pluginParameter
     * @param requestId
     * @param tag
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/verifyCertificateEx")
    @WebResult(name = "verifyCertificateExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "verifyCertificateEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifyCertificateEx")
    @ResponseWrapper(localName = "verifyCertificateExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifyCertificateExResponse")
    public DVSResponseEx verifyCertificateEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "refreshCRLs", targetNamespace = "http://www.dictao.com/DVS/Interface")
        int refreshCRLs,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "certificate", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String certificate,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param transactionId
     * @param refreshCRLs
     * @param scope
     * @param requestId
     * @param tag
     * @param userIdentifier
     * @param userPassword
     * @param properties
     * @param authenticationType
     * @param pluginParameter
     * @param sessionId
     * @param token
     * @param authenticationFormat
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/verifyAuthenticationEx")
    @WebResult(name = "verifyAuthenticationExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "verifyAuthenticationEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifyAuthenticationEx")
    @ResponseWrapper(localName = "verifyAuthenticationExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.VerifyAuthenticationExResponse")
    public DVSResponseEx verifyAuthenticationEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "refreshCRLs", targetNamespace = "http://www.dictao.com/DVS/Interface")
        int refreshCRLs,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "authenticationFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationFormat,
        @WebParam(name = "authenticationType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationType,
        @WebParam(name = "sessionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String sessionId,
        @WebParam(name = "userIdentifier", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String userIdentifier,
        @WebParam(name = "scope", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String scope,
        @WebParam(name = "token", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType token,
        @WebParam(name = "userPassword", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String userPassword,
        @WebParam(name = "properties", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType properties,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param transactionId
     * @param pluginParameter
     * @param requestId
     * @param tag
     * @param userIdentifier
     * @param authenticationFormat
     * @param properties
     * @param authenticationType
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/getAuthenticationChallengeEx")
    @WebResult(name = "getAuthenticationChallengeExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "getAuthenticationChallengeEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.GetAuthenticationChallengeEx")
    @ResponseWrapper(localName = "getAuthenticationChallengeExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.GetAuthenticationChallengeExResponse")
    public DVSResponseEx getAuthenticationChallengeEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "authenticationFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationFormat,
        @WebParam(name = "authenticationType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationType,
        @WebParam(name = "userIdentifier", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String userIdentifier,
        @WebParam(name = "properties", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType properties,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param pluginParameter
     * @param archiveId
     * @param requestId
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSArchiveResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/getArchiveEx")
    @WebResult(name = "getArchiveExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "getArchiveEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.GetArchiveEx")
    @ResponseWrapper(localName = "getArchiveExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.GetArchiveExResponse")
    public DVSArchiveResponseEx getArchiveEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "archiveId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String archiveId,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param scope
     * @param transactionId
     * @param pluginParameter
     * @param requestId
     * @param tag
     * @param userIdentifier
     * @param authenticationFormat
     * @param properties
     * @param authenticationType
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/prepareAuthenticationRequestEx")
    @WebResult(name = "prepareAuthenticationRequestExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "prepareAuthenticationRequestEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.PrepareAuthenticationRequestEx")
    @ResponseWrapper(localName = "prepareAuthenticationRequestExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.PrepareAuthenticationRequestExResponse")
    public DVSResponseEx prepareAuthenticationRequestEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "authenticationFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationFormat,
        @WebParam(name = "authenticationType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String authenticationType,
        @WebParam(name = "userIdentifier", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String userIdentifier,
        @WebParam(name = "scope", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String scope,
        @WebParam(name = "properties", targetNamespace = "http://www.dictao.com/DVS/Interface")
        DataType properties,
        @WebParam(name = "pluginParameter", targetNamespace = "http://www.dictao.com/DVS/Interface")
        ArrayOfPluginParameterStruct pluginParameter);

    /**
     * 
     * @param pinServer
     * @param challengeType
     * @param challengeFormat
     * @param transactionId
     * @param requestId
     * @param tag
     * @param userIdentifier
     * @param keyContainerXmlB64
     * @param properties
     * @param customizationFormat
     * @param customizationType
     * @param challenge
     * @param sessionId
     * @return
     *     returns org.kiwi.dictao.webservices.dvs.DVSResponseEx
     */
    @WebMethod(action = "http://www.dictao.com/DVS/Interface/customizeTokenEx")
    @WebResult(name = "customizeTokenExResult", targetNamespace = "http://www.dictao.com/DVS/Interface")
    @RequestWrapper(localName = "customizeTokenEx", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.CustomizeTokenEx")
    @ResponseWrapper(localName = "customizeTokenExResponse", targetNamespace = "http://www.dictao.com/DVS/Interface", className = "org.kiwi.dictao.webservices.dvs.CustomizeTokenExResponse")
    public DVSResponseEx customizeTokenEx(
        @WebParam(name = "requestId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String requestId,
        @WebParam(name = "transactionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String transactionId,
        @WebParam(name = "tag", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String tag,
        @WebParam(name = "customizationFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String customizationFormat,
        @WebParam(name = "customizationType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String customizationType,
        @WebParam(name = "sessionId", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String sessionId,
        @WebParam(name = "userIdentifier", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String userIdentifier,
        @WebParam(name = "keyContainerXmlB64", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String keyContainerXmlB64,
        @WebParam(name = "challenge", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String challenge,
        @WebParam(name = "challengeFormat", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String challengeFormat,
        @WebParam(name = "challengeType", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String challengeType,
        @WebParam(name = "properties", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String properties,
        @WebParam(name = "PINServer", targetNamespace = "http://www.dictao.com/DVS/Interface")
        String pinServer);

}
