
package org.kiwi.dictao.webservices.d2slegacy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Dictao Signature Server v2.1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "D2S", targetNamespace = "http://www.dictao.com/D2S/Interface", wsdlLocation = "file:/C:/local_projects/java/librairies/dictao/wsdl/D2SInterfaceLegacy.wsdl")
public class D2S
    extends Service
{

    private final static URL D2S_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.kiwi.dictao.webservices.d2slegacy.D2S.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.kiwi.dictao.webservices.d2slegacy.D2S.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/local_projects/java/librairies/dictao/wsdl/D2SInterfaceLegacy.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/local_projects/java/librairies/dictao/wsdl/D2SInterfaceLegacy.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        D2S_WSDL_LOCATION = url;
    }

    public D2S(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public D2S() {
        super(D2S_WSDL_LOCATION, new QName("http://www.dictao.com/D2S/Interface", "D2S"));
    }

    /**
     * 
     * @return
     *     returns D2SSoap
     */
    @WebEndpoint(name = "D2SSoap")
    public D2SSoap getD2SSoap() {
        return super.getPort(new QName("http://www.dictao.com/D2S/Interface", "D2SSoap"), D2SSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns D2SSoap
     */
    @WebEndpoint(name = "D2SSoap")
    public D2SSoap getD2SSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dictao.com/D2S/Interface", "D2SSoap"), D2SSoap.class, features);
    }

}
