
package org.kiwi.dictao.webservices.d3s.Authority;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SafeboxPort", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2/Authority")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SafeboxPort {


    /**
     * 
     * @param containerPath
     * @param defaultOrgunitPath
     * @param safebox
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:create")
    @WebResult(name = "createdResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "createSafebox", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateSafebox")
    @ResponseWrapper(localName = "createSafeboxResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.CreateResponse")
    public String createSafebox(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "containerPath", targetNamespace = "")
        String containerPath,
        @WebParam(name = "safebox", targetNamespace = "")
        Safebox safebox,
        @WebParam(name = "defaultOrgunitPath", targetNamespace = "")
        String defaultOrgunitPath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.Safebox
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:read")
    @WebResult(name = "safebox", targetNamespace = "")
    @RequestWrapper(localName = "readSafebox", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Read")
    @ResponseWrapper(localName = "readSafeboxResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ReadSafeboxResponse")
    public Safebox readSafebox(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param safebox
     * @param motivation
     * @param applicantPath
     * @return
     *     returns java.lang.String
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:update")
    @WebResult(name = "updatedResourcePath", targetNamespace = "")
    @RequestWrapper(localName = "updateSafebox", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateSafebox")
    @ResponseWrapper(localName = "updateSafeboxResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.UpdateResponse")
    public String updateSafebox(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath,
        @WebParam(name = "safebox", targetNamespace = "")
        Safebox safebox)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param motivation
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:delete")
    @RequestWrapper(localName = "deleteSafebox", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.Delete")
    @ResponseWrapper(localName = "deleteSafeboxResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.DeleteResponse")
    public void deleteSafebox(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param orderBy
     * @param criteria
     * @param searchPath
     * @param motivation
     * @param maxResult
     * @param applicantPath
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.FindSafeboxesResponse
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:find")
    @WebResult(name = "findSafeboxesResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority")
    @RequestWrapper(localName = "findSafeboxes", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.FindSafeboxes")
    @ResponseWrapper(localName = "findSafeboxesResponseContent", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.FindSafeboxesResponseContent")
    public FindSafeboxesResponse findSafeboxes(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "searchPath", targetNamespace = "")
        String searchPath,
        @WebParam(name = "criteria", targetNamespace = "")
        List<Criterion> criteria,
        @WebParam(name = "orderBy", targetNamespace = "")
        List<OrderBy> orderBy,
        @WebParam(name = "maxResult", targetNamespace = "")
        int maxResult)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param cursor
     * @return
     *     returns org.kiwi.dictao.webservices.d3s.Authority.FindSafeboxesResponse
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:next")
    @WebResult(name = "findSafeboxesResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority")
    @RequestWrapper(localName = "nextSafeboxes", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.NextSafeboxes")
    @ResponseWrapper(localName = "nextSafeboxesResponseContent", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.NextSafeboxesResponseContent")
    public FindSafeboxesResponse nextSafeboxes(
        @WebParam(name = "cursor", targetNamespace = "")
        byte[] cursor)
        throws EnvironmentFaultException, UserFaultException
    ;

    /**
     * 
     * @param resourcePath
     * @param accessPermissions
     * @param motivation
     * @param applicantPath
     * @throws EnvironmentFaultException
     * @throws UserFaultException
     */
    @WebMethod(action = "Safebox:changeAccessPermissions")
    @RequestWrapper(localName = "changeAccessPermissions", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ChangeAccessPermissions")
    @ResponseWrapper(localName = "changeAccessPermissionsResponse", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority", className = "org.kiwi.dictao.webservices.d3s.Authority.ChangeAccessPermissionsResponse")
    public void changeAccessPermissions(
        @WebParam(name = "applicantPath", targetNamespace = "")
        String applicantPath,
        @WebParam(name = "motivation", targetNamespace = "")
        String motivation,
        @WebParam(name = "resourcePath", targetNamespace = "")
        String resourcePath,
        @WebParam(name = "AccessPermissions", targetNamespace = "")
        AccessPermissions accessPermissions)
        throws EnvironmentFaultException, UserFaultException
    ;

}
