
package org.kiwi.dictao.webservices.d3s.Authority;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UserFaultElement", targetNamespace = "http://www.dictao.com/d3s/wsdl/v2.1/Authority")
public class UserFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UserFaultException(String message, UserFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserFaultException(String message, UserFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.kiwi.dictao.webservices.d3s.Authority.UserFaultInfo
     */
    public UserFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
